routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Front routes
Route::group(['middleware' => 'web'], function (){
    Route::get('/','FrontController@index')->name('front');
    Route::get('/products','ProductController@products')->name('products');
    Route::get('/product/{id}','ProductController@single_product')->name('product');
    Route::get('/contact','ContactController')->name('contact');
//     Show payment form
    Route::get('/payment/add-funds/paypal', 'PaymentController@showForm');

// Post payment details for store/process API request
    Route::post('/payment/add-funds/paypal', 'PaymentController@store');

// Handle status
    Route::get('/payment/add-funds/paypal/status', 'PaymentController@getPaymentStatus');

// /Show payment form
    Route::auth();
});
// Front routes

//User dashboard
Route::group(['prefix' => 'cart', 'middleware' => 'auth'], function (){
    Route::get('/','CartController@index')->name('cart');
});
//User dashboard



// Admin panel
Route::group(['prefix'=>'admin', 'middleware' => ['auth', 'role']], function() {
    Route::get('/', function () {
        return view('home');
    })->name('admin-panel');
//category
    Route::get('/category-list',['uses'=>'Admin\CategoryController@show','as'=>'cat-list']);
    Route::get ('/category-add',['uses'=>'Admin\CategoryController@add','as'=>'cat-add']);
    Route::post('/category-create',['uses'=>'Admin\CategoryController@create','as'=>'cat-create']);
    Route::get('/category-update/{id}/edit',['uses'=>'Admin\CategoryController@update','as'=>'cat-update']);
    Route::patch('/category-handler/{id}',['uses'=>'Admin\CategoryController@category_create','as'=>'category-handler']);
    Route::delete('/category-delete/{id}',['uses'=>'Admin\CategoryController@delete','as'=>'category-delete']);
    Route::resource('/brands','Admin\BrandController');
    Route::resource('/sub_category','Admin\SubCategoryController');
    Route::resource('/products','Admin\ProductController');
});
// Admin panel

// Данный маршрут сработает при переходе из эл.почты в приложение, для подтверждения эл.почты
Route::get('/verify/token/{token}', 'Auth\VerificationController@verify')->name('auth.verify');
Route::get('/verify/resend', 'Auth\VerificationController@resend')->name('auth.verify.resend');

Auth::routes();









// Temporary route for inserting information in tables
//Route::get('/temp', 'TempController@insert');

resources/views/admin/brands.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-xs-12">
        {{--@if(session()->has('message'))--}}
            {{--<div class="alert alert-success">--}}
                {{--{{ session()->get('message') }}--}}
            {{--</div>--}}
        {{--@endif--}}
        <br />
        <h1>All Brands</h1>
        <hr>
    </div>
    <div class="col-xs-12">
        <a href="{{route('brands.create')}}" class="btn btn-success">
            Add Brands
        </a>
        <br><br>
    </div>
    <div class="col-xs-12">
        <table class="table table-bordered table-hover table-responsive">
            <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Created at</th>
                <th>Updated at</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
            </thead>
            <tbody>
            @if(isset($brands) && is_object($brands))
                @foreach($brands as $brand)
                    <tr>
                        <td>{{$brand['id']}}</td>
                        <td id="{{$brand['id']}}">{{$brand->Brand}}</td>
                        <td>{{$brand->created_at}}</td>
                        <td>{{$brand->updated_at}}</td>
                        <td>
                            <a href="{{route('brands.edit',['id'=>$brand->id])}}" data-toggle="tooltip"  title="Update Brand" class="btn btn-info btn-sm"  role="button">Edit</a>

                        </td>
                        <td>
                            {{--delete--}}
                            <form action="{{route('brands.destroy',$brand['id'])}}" method="post">
                                {{csrf_field()}}
                                <input name="_method" type="hidden" value="DELETE">
                                <!-- Button trigger modal -->
                                <button type="button" onclick=" {
                                {{--                                        var a = {{$sub['id']}}--}}
                                        document.getElementById('sp').innerHTML = document.getElementById('{{$brand['id']}}').innerHTML;

                                        }" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                                    Delete
                                </button>

                                <!-- Modal -->
                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Are you Sure? </h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Be careful,cause of you can't reBack DATA
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-primary">Delete</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </td>
                    </tr>
                @endforeach
            @endif
            </tbody>
        </table>
        {{$brands->links()}}
    </div>
@endsection

resources/views/admin/brands_create.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-xs-12">
        <h1>Add Brand</h1>
        @if(session()->has('message'))
            <div class="alert alert-success">
                {{ session()->get('message') }}
            </div>
        @endif
        <hr>
    </div>
    <div class="col-xs-12">
        <form action="{{ route('brands.store') }}" method="post">
            {{ @csrf_field() }}
            <div class="form-group">
                <label for="brand-add">Add new Brand</label>
                <input name="brand" type="text" class="form-control" id="brand-add" placeholder="Add new Brand...">
            </div>
            <button type="submit" class="btn btn-success">
                <i class="fa fa-plus" aria-hidden="true"></i>
                Add Brand
            </button>
        </form>

        <br />
        <br>
        <br>
        <div class="col-lg-1 ">
            <a href="{{ url('admin/brands') }}" class="btn btn-success" style="margin-left: 200%;margin-top: -190px" >Go to Brands</a>
        </div>
    </div>

@endsection

resources/views/admin/brands_destroy.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        @if(session()->has('message'))
            <div class="alert alert-success">
                {{ session()->get('message') }}
            </div>
        @endif
        <br />

            <h1> The Data was successfully deleted</h1>
        <div class="col-lg-1">
            <a href="{{ url('admin/brands') }}" class="btn btn-success" >Go to Brands</a>
        </div>

    </div>

@endsection

resources/views/admin/brands_edit.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <h1 class="text-center">Edit {{$brand['Brand']}}</h1>
<br>
        <hr>
        @if(session()->has('message'))
            <div class="alert alert-success">
                {{ session()->get('message') }}
            </div>
        @endif
        <div class="row">
            {{--form group--}}
            <form action="{{route('brands.update',$brand['id'])}}" method="post">
                {{ csrf_field() }}
                <div class="col-lg-3">
                    {{--<input name="_method" type="hidden" value="PATCH">--}}
                    {{method_field('PUT')}}
                    <div class="input-group">
                        <input type="text" class="form-control" name="brand" value="{{$brand['Brand']}}" placeholder="Title" style="width: 120%">
                    </div>
                </div>
                <div class="col-lg-1">
                    <button type="submit" class="btn btn-danger">Update</button>
                </div>
            </form>
            <div class="col-lg-1">
                <a href="{{ url('admin/brands') }}" class="btn btn-success" >Go to Brands</a>
            </div>
        </div>



    </div>
    @endsection

resources/views/admin/category-add.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-xs-12">
        <h1>Add category</h1>
        <hr>
    </div>
    <div class="col-xs-12">
        <form action="{{ route('cat-create') }}" method="post">
            {{ @csrf_field() }}
            <div class="form-group">
                <label for="category-add">Add new category</label>
                <input name="title" type="text" class="form-control" id="category-add" placeholder="Add new category...">
            </div>
            <button type="submit" class="btn btn-success">
                <i class="fa fa-plus" aria-hidden="true"></i>
                Add category
            </button>
        </form>
    </div>
@endsection

resources/views/admin/category-delete.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        @if(session()->has('message'))
            <div class="alert alert-success">
                {{ session()->get('message') }}
            </div>
        @endif
        <br />
        <div class="col-lg-1">
            <a href="{{ url('admin/category-list') }}" class="btn btn-success" >Go to Categories</a>
        </div>

    </div>

        @endsection

resources/views/admin/category-handler.blade.php
@extends('layouts.app')
@section('content')


    <div class="container">
        <h1 class="text-center">Your new update is {{$title['title']}}</h1>

        <div class="col-xs-12">
            <table class="table table-bordered table-hover table-responsive">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Created at</th>
                    <th>Updated at</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                        <tr>
{{--                            @foreach($title as $cat)--}}
                            <td>{{$title['id']}}</td>
                            <td>{{$title['title']}}</td>
                            <td>{{$title['created_at']}}</td>
                            <td>{{$title['updated_at']}}</td>
                            <td>
                                <a href="{{route('cat-update',['id'=>$title->id])}}" data-toggle="tooltip"  title="Update category" class="btn btn-info btn-sm"  role="button">Edit</a>

                            </td>
                            <td>
                                <form action="{{route('category-delete',$title['id'])}}" method="post">
                                    {{csrf_field()}}
                                    <input name="_method" type="hidden" value="DELETE">
                                    <button class="btn btn-danger"  type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                </tbody>
            </table>
        </div>

        <div class="row">
            {{--form group--}}

            <div class="col-lg-1">
                <a href="{{ url('admin/category-list') }}" class="btn btn-success" >Go to Categories</a>
            </div>
        </div>



    </div>



    @endsection

resources/views/admin/products.blade.php
@extends('layouts.app')
@section('content')


    <div class="col-xs-12">
        <br/>
        <h1>All Products</h1>
        <hr>
    </div>
    <div class="col-xs-12">
        <a href="{{route('products.create')}}" class="btn btn-success">
            Add Products
        </a>
        <br><br>
    </div>
    <div class="col-xs-12">
        <table class="table table-bordered table-hover table-responsive" id="myTable">
            <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Brand</th>
                <th>Condition</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Order_id</th>
                <th>Images</th>
                <th>Description</th>
                <th>Meta_Desc</th>
                <th>Meta_Keys</th>
                <th>Belongs to Sub</th>
                <th>Created at</th>
                <th>Updated at</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
            </thead>
            <tbody>
            @if(isset($prods) && is_object($prods))
                @foreach($prods as $prod)
                    <tr>
                        <td>{{$prod['id']}}</td>
                        <td id="{{$prod->id}}">{{$prod->title}}</td>
                        <td>{{$prod->brands->Brand}}</td>
                        <td>{{$prod->condition}}</td>
                        {{--$prod->condition its mean weither its new or old or normal product--}}
                        <td>{{$prod->quantity}}</td>
                        <td>{{$prod->price}}</td>
                        <td>{{$prod->web_id}}</td>
                        <td>{{$prod->posters}}</td>
                        <td>{{$prod->description}}</td>
                        <td>{{$prod->meta_d}}</td>
                        <td>{{$prod->meta_k}}</td>
                        <td>{{$prod->sub__categories->common}}</td>
                        <td>{{$prod->created_at}}</td>
                        <td>{{$prod->updated_at}}</td>
                        <td>
                            {{--<a href="{{route('sub_category.edit',['id'=>$sub->id])}}" data-toggle="tooltip"--}}
                               {{--title="Update Sub Category" class="btn btn-info btn-sm" role="button">Edit</a>--}}

                        {{--</td>--}}
                        {{--<td>--}}
                            {{--{{$a= }}'<span style="color: red">{{$sub->name}}</span>'--}}
                            {{--<form action="{{route('sub_category.destroy',$sub['id'])}}" method="post"--}}
                                  {{--onsubmit="return confirm('You are going to delete  {{$sub->name}}')">--}}
                                {{--{{csrf_field()}}--}}
                                {{--{{method_field('DELETE')}}--}}
                                {{--<button type="submit" class="btn btn-danger">Delete</button>--}}
                            {{--</form>--}}
                        </td>
                    </tr>
                @endforeach
            @endif
            </tbody>
        </table>
        {{$prods->links()}}
    </div>



    @endsection

resources/views/admin/products_create.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-xs-12">
        <h1>Add Products</h1>
        <hr>
    </div>
    <div class="col-xs-12">
        <form action="{{ route('products.store') }}" method="post" enctype="multipart/form-data">
            {{ @csrf_field() }}
            <div class="form-group">
                <label for="brand-add">Title</label>
                <input name="title" type="text" class="form-control" placeholder="Add Title...">
                {{--available--}}
                <hr>
                <h5>Availability</h5>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="availability" id="inlineRadio1" value="yes">
                    <label class="form-check-label" for="inlineRadio1">Available</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="availability" id="inlineRadio2" value="no">
                    <label class="form-check-label" for="inlineRadio2">Don`t Available</label>
                </div>
                {{--end available--}}
                <hr>
                {{--condition--}}
                <label for="condition">Condition</label>
                <input id="condition" name="condition" type="text" class="form-control" placeholder="Add Condition...">
                {{--end condition--}}
                {{--quantity--}}
                <hr>
                <h4>Quantity</h4>
                <select name="quantity" class="custom-select" style="width: 10%;height: 32px">
                @for($i = 0;$i<=1000;$i++)
                    <option value="{{$i}}">{{$i}}</option>
                  @endfor
                </select>
                {{--end quantity--}}
                <hr>
                {{--price--}}
                <label for="price">Price</label>
                <input id="price" name="price" type="text" class="form-control" placeholder="Add Price...">
                {{--end price--}}
                <hr>
                {{--web_id--}}
                <h5>Click on button to generate web_id</h5>
                <button type="button" id="web" name="web_id" onclick=" {
                       $('#web').val((new Date().getSeconds()).toString() + (Math.floor(Math.random()*999)+10).toString()+(new Date().getMinutes()).toString()+(new Date().getHours()).toString()+(new Date().getDate()).toString()) ;
                       $('#web').html($('#web').val())
                        }" class="btn btn-info">Click Me</button>
                {{--End web_id--}}
                <hr>
                {{--poster--}}
                    {{--<input type="file" id="poster"  class="custom-file-input" name="poster[]" multiple/>--}}
                <input type="file" class="filestyle" id="poster"  name="poster[]" multiple/>
                {{--End poster--}}
                <hr>
                {{--description--}}
                <h4 >Description</h4>
                <textarea class="form-control" title="description" name="description" id="description" rows="10" cols="80">
            </textarea>
                {{--end description--}}
                <hr>
            </div>
            <button type="submit" class="btn btn-success">
                <i class="fa fa-plus" aria-hidden="true"></i>
                Add Product
            </button>
        </form>

        <br />
        <br>
        <br>
        <div class="col-lg-1 ">
            <a href="{{ url('admin/products') }}" class="btn btn-success" style="margin-left: 200%;margin-top: -190px" >Go to Products</a>
        </div>
    </div>

@endsection

resources/views/admin/sub_category.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-xs-12">
        <br/>
        <h1>All Sub_Categories</h1>
        <hr>
    </div>
    <div class="col-xs-12">
        <a href="{{route('sub_category.create')}}" class="btn btn-success">
            Add Sub_Categories
        </a>
        <br><br>
    </div>
    <div class="col-xs-12">
        <table class="table table-bordered table-hover table-responsive" id="myTable">
            <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>description</th>
                <th>Keys</th>
                <th>Belongs to</th>
                <th>Created at</th>
                <th>Updated at</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
            </thead>
            <tbody>
            @if(isset($subs) && is_object($subs))
                @foreach($subs as $sub)
                    <tr>
                        <td>{{$sub['id']}}</td>
                        <td id="{{$sub->id}}">{{$sub->name}}</td>
                        <td>{{$sub->meta_d}}</td>
                        <td>{{$sub->meta_k}}</td>
                        <td>{{$sub->category->title}}</td>
                        <td>{{$sub->created_at}}</td>
                        <td>{{$sub->updated_at}}</td>
                        <td>
                            <a href="{{route('sub_category.edit',['id'=>$sub->id])}}" data-toggle="tooltip"
                               title="Update Sub Category" class="btn btn-info btn-sm" role="button">Edit</a>

                        </td>
                        <td>
                            {{--{{$a= }}'<span style="color: red">{{$sub->name}}</span>'--}}
                            <form action="{{route('sub_category.destroy',$sub['id'])}}" method="post"
                                  onsubmit="return confirm('You are going to delete  {{$sub->name}}')">
                                {{csrf_field()}}
                                {{method_field('DELETE')}}
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            @endif
            </tbody>
        </table>
        {{$subs->links()}}
    </div>

@endsection

resources/views/admin/sub_category_create.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-xs-12">
        <h1>Add Sub_Category</h1>
        @if(session()->has('message'))
            <div class="alert alert-success">
                {{ session()->get('message') }}
            </div>
        @endif
        <hr>
    </div>
    <div class="col-xs-12">
        <form action="{{ route('sub_category.store') }}" method="post">
            {{ @csrf_field() }}
            <div class="form-group">
                <label for="brand-add">Add new Sub_Category</label>
                <input name="sub_category" type="text" class="form-control" id="sub-add" placeholder="Add new Sub Category...">
                <input type="text" name="sub_desc" placeholder="Describe your sub category" class="form-control" id="sub-desc">
                <input type="text" name="sub_key" placeholder="Meta keys for your sub category" class="form-control" id="sub-key">
                <select class="form-control mt-5" name="category" title="category">

                    @if($categories->count())

                        @foreach($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->title }}</option>
                        @endforeach
                    @endif

                </select>
            </div>
            <button type="submit" class="btn btn-success">
                <i class="fa fa-plus" aria-hidden="true"></i>
                Add Sub_Category
            </button>
        </form>

        <br />
        <br>
        <br>
        <div class="col-lg-1 mb-20">
            <a href="{{ url('admin/sub_category') }}" class="btn btn-success" style="margin-left: 200%;margin-top: -150px" >Go to Sub_Categories</a>
        </div>
    </div>

@endsection

resources/views/admin/sub_category_edit.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <h1 class="text-center">Edit {{$sub['name']}}</h1>
        <br>
        <hr>
        @if(session()->has('message'))
            <div class="alert alert-success">
                {{ session()->get('message') }}
            </div>
        @endif
        <div class="row">
            {{--form group--}}
            <form action="{{route('sub_category.update',$sub['id'])}}" method="post">
                {{ csrf_field() }}
                <div class="col-lg-3">
                    {{--<input name="_method" type="hidden" value="PATCH">--}}
                    {{method_field('PUT')}}
                    <div class="input-group">
                        <input type="text" class="form-control" name="sub_category" value="{{$sub['name']}}" placeholder="sub name">
                        <input type="text" class="form-control" name="sub_desc" value="{{$sub['meta_d']}}" placeholder="sub description">
                        <input type="text" class="form-control" name="sub_key" value="{{$sub['meta_k']}}" placeholder="sub meta key">
                        <select class="form-control mt-5" name="category" title="category">

                            @if($categories->count())

                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->title }}</option>
                                @endforeach
                            @endif

                        </select>
                    </div>
                </div>
                <div class="col-lg-1">
                    <button type="submit" class="btn btn-danger">Update</button>
                </div>
            </form>
            <div class="col-lg-1">
                <a href="{{ url('admin/sub_category') }}" class="btn btn-success" >Return Back</a>
            </div>
        </div>



    </div>
@endsection

resources/views/admin/sub_category_show.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-xs-12">
        @if(session()->has('message'))
            <div class="alert alert-success">
                {{ session()->get('message') }}
            </div>
        @endif
        <br />
        <h1>{{$sub->name}} Sub_Categories was successfully updated</h1>
        <hr>
    </div>
    <div class="col-xs-12">
        <a href="{{ url('admin/sub_category') }}" class="btn btn-success" >Return Back</a>
        <br><br>
    </div>
    <div class="col-xs-12">
        <table class="table table-bordered table-hover table-responsive">
            <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>description</th>
                <th>Keys</th>
                <th>Belongs to</th>
                <th>Created at</th>
                <th>Updated at</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
            </thead>
            <tbody>
                    <tr>
                        <td>{{$sub['id']}}</td>
                        <td>{{$sub->name}}</td>
                        <td>{{$sub->meta_d}}</td>
                        <td>{{$sub->meta_k}}</td>
                        <td>{{$sub->category->title}}</td>
                        <td>{{$sub->created_at}}</td>
                        <td>{{$sub->updated_at}}</td>
                        <td>
                            <a href="{{route('sub_category.edit',['id'=>$sub->id])}}" data-toggle="tooltip"  title="Update Sub Category" class="btn btn-info btn-sm"  role="button">Edit</a>

                        </td>
                        <td>
                            {{--delete--}}
                            <form action="{{route('sub_category.destroy',$sub['id'])}}" method="post">
                                {{csrf_field()}}
                                {{method_field('DELETE')}}
                                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                                    Delete
                                </button>

                                {{--<!-- Modal -->--}}
                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Are you Sure? </h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                 You are going to delete <span  style="color: red; text-transform: uppercase">{{$sub->name}}</span>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-primary">Delete</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </td>
                    </tr>
            </tbody>
        </table>
    </div>
@endsection