routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Front routes
Route::group(['middleware' => 'web'], function (){
    Route::get('/','FrontController@index')->name('front');
    Route::get('/products','ProductController@products')->name('products');
    Route::get('/product/{id}','ProductController@single_product')->name('product');
    Route::get('/contact','ContactController')->name('contact');
//     Show payment form
    Route::get('/payment/add-funds/paypal', 'PaymentController@showForm');

// Post payment details for store/process API request
    Route::post('/payment/add-funds/paypal', 'PaymentController@store');

// Handle status
    Route::get('/payment/add-funds/paypal/status', 'PaymentController@getPaymentStatus');

// /Show payment form
    Route::auth();
});
// Front routes

//User dashboard
Route::group(['prefix' => 'cart', 'middleware' => 'auth'], function (){
    Route::get('/','CartController@index')->name('cart');
});
//User dashboard



// Admin panel
Route::group(['prefix'=>'admin', 'middleware' => ['auth', 'role']], function() {
    Route::get('/', function () {
        return view('home');
    })->name('admin-panel');
//category
    Route::get('/category-list',['uses'=>'Admin\CategoryController@show','as'=>'cat-list']);
    Route::get ('/category-add',['uses'=>'Admin\CategoryController@add','as'=>'cat-add']);
    Route::post('/category-create',['uses'=>'Admin\CategoryController@create','as'=>'cat-create']);
    Route::get('/category-update/{id}/edit',['uses'=>'Admin\CategoryController@update','as'=>'cat-update']);
    Route::patch('/category-handler/{id}',['uses'=>'Admin\CategoryController@category_create','as'=>'category-handler']);
    Route::delete('/category-delete/{id}',['uses'=>'Admin\CategoryController@delete','as'=>'category-delete']);
    Route::resource('/brands','Admin\BrandController');
    Route::resource('/sub_category','Admin\SubCategoryController');
    Route::resource('/products','Admin\ProductController');
});
// Admin panel

// Данный маршрут сработает при переходе из эл.почты в приложение, для подтверждения эл.почты
Route::get('/verify/token/{token}', 'Auth\VerificationController@verify')->name('auth.verify');
Route::get('/verify/resend', 'Auth\VerificationController@resend')->name('auth.verify.resend');

Auth::routes();









// Temporary route for inserting information in tables
//Route::get('/temp', 'TempController@insert');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">

    {{--errors table--}}
    @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div><br />
    @endif
    {{--end alert table--}}
    <hr>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                  <li><a href="{{route('cat-list')}}">Category</a></li>
                    <li><a href="{{route('sub_category.index')}}">Subcategory</a></li>
                    <li><a href="{{route('brands.index')}}">Brand</a></li>
                    <li><a href="{{route('products.index')}}">Products</a></li>&nbsp;
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @guest
                        <li><a href="{{ route('login') }}">Login</a></li>
                        <li><a href="{{ route('register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false" aria-haspopup="true" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                          style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                @include('layouts.partials._notifications')
            </div>
        </div>
    </div>
    @yield('content')
</div>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
<script type="text/javascript" src="{{asset('js/bootstrap-filestyle.min.js')}}"> </script>
<script src="{{asset('vendor/unisharp/laravel-ckeditor/ckeditor.js')}}"></script>
<script>
    CKEDITOR.replace( 'description' );
</script>
</body>
</html>

resources/views/layouts/front.blade.php
<!DOCTYPE html>
<html lang="{{app()->getLocale()}}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#178EA5">
    <meta name="csrf-token" content="{{csrf_token()}}">
    <meta name="register_route" content="{{route('register')}}">
    <meta name="login_route" content="{{route('login')}}">
    <title>@yield('title') | Core-Systems</title>
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/font-awesome.min.css')}}">
    @yield('css_plugins')
    <link rel="stylesheet" href="{{asset('css/index.css')}}">
    <link rel="stylesheet" href="{{asset('css/media.css')}}">

    <link rel="shortcut icon" type="image/png" href="{{asset('images/favicon.ico')}}">
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

@include('layouts.partials._notifications')

<!-- Button to top -->
@include('layouts.partials.button_to_top')
<!-- /Button to top -->

<!-- Header -->
@include('layouts.partials.header')
<!-- /Header -->

<!-- Carousel -->
@yield('carousel')
<!-- /Carousel -->

<!-- Main -->
<div class="container">
    <div class="row">
        <!-- Main Information -->
    @yield('content')
    <!-- /Main Information-->
    </div>
</div>
<!-- /Main -->

<!-- Footer -->
@include('layouts.partials.footer')
<!-- /Footer -->

<!-- Login and Register modal -->
@include('layouts.partials.login_register_modal')
<!-- /Login and Register modal -->

{{--<!-- Additonal modals -->--}}
@yield('modals')
{{--<!-- /Additonal modals-->--}}

<script src="{{asset('js/jquery-3.2.1.min.js')}}"></script>
<script src="{{asset('js/bootstrap.min.js')}}"></script>
@yield('js_plugins')
<script src="{{asset('js/main.js')}}"></script>

<!-- Google map -->
@include('layouts.partials.google_map_script')
<!-- /Google map -->
</body>
</html>